apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
  - http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              name: http
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              name: http
