apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  labels:
    app: ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app
          image: itisshajith/test:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred